name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: jaid/action-npm-install@v1.2.1
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: dist/